version: '3'

services:
  backend:
    container_name: backend
    build: ./classroom-backend/.
    ports:
      - '3000:3000'
    env_file:
      - ./classroom-backend/.env
    environment:
      - FRONTEND_URL=http://frontend:80
      - ENABLE_CORS=false

  frontend:
    container_name: frontned
    build: ./classroom-frontend/.
    ports:
      - "8080:80"
    environment:
      - VITE_BACKEND_URL="http://localhost:8080/api"
